### ISSUE TITLE
[BUG]: Custom probe results in error

### ISSUE THREAD

**Issue by pmoscode** [pmoscode-helm/emby#7]
### Description of the bug

When anything else than httpGet ist set, it results in "livenessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type".

The predifined probe is not replaced by the configured one...

### Steps To Reproduce

Define in values.yaml:

```yaml
readinessProbe:
  tcpSocket:
    port: http
```
